version: "3"

services:
  app:
    image: docker-contact-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages  
      - ./public:/app/public  
      - ./app:/app/app  
      - ./prisma:/app/prisma  