export const Envs = {
  NODE_ENV: process.env.NODE_ENV,
  BASE_URL: process.env.BASE_URL,
  CSRF_SECRET: process.env.CSRF_SECRET,
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  NEXT_PUBLIC_RECAPTCHA_SECRET_KEY:
    process.env.NEXT_PUBLIC_RECAPTCHA_SECRET_KEY,
};
